Build/MortgageApplication/build/deploy.groovy
When the workDir is not mentioned in build.properties and supplied via command line, the original version failed because of null pointer exception. So I added a null check before moving the value.
=> buildProperties.workDir - null pointer execption

Utilities/Jenkins/README.md, Utilities/Jenkins/git-jenkins2.sh
This is regarding the raised issue #31 .
When managing https credentials or a ssh passphrase in Jenkins, the Git plugins have changed their behaviour causing issue FATAL: Invalid id exception.
The root cause is a wrong encoding of files in the build work directory.
=> New git-jenkins2.sh

Build/MortgageApplication/build/deploy.groovy
Current code generates a new property for every version
property name='MortageApplication-master-build.20200819.021543.015' value='https://example.com:9443/dbb/rest/buildResult/1000' 
But this is wrong. In UCD, the property name needs to be same across versions. Only the property value should change. Otherwise, UCD creates unnecessary duplicate properties and versions end up with too many properties. 
New code should generate 
property name='MortageApplication-master-build-buildResultUrl' value='https://example.com:9443/dbb/rest/buildResult/1000' 
Here the property name will be always constant.
=> Changing property name at the manifest level

Build/MortgageApplication/build/deploy.groovy
Even though MortgageApplication will be replaced with a smaller sample application in the next release of DBB and `deploy.groovy` has already been replaced by the [CreateUCDComponentVersion](https://github.com/IBM/dbb/tree/master/Pipeline/CreateUCDComponentVersion) sample, it should still update this sample since we missed updating it in DBB v1.0.8 release when we introduced the changes to CopyToPDS.
=> Add support for Copy_TO_PDS build report records to deploy.groovy

Utilities/Jenkins/README.md, Utilities/Jenkins/git-jenkins3.sh
Jenkins Git client now supports to set the target codepages as environment variables. I have enhanced the documentation to explain the different scenarios.
Additionally, added git-jenkins3.sh to supports http communication for older versions of the plugin.
=> Updated documentation of Jenkins scripts

Pipeline/RunIDZCodeReview/RunCodeReview.groovy, Pipeline/RunIDZCodeReview/codereview.properties
Please see an enhancement to provide a custom SYSLIB concatenation through the properties file. See #71 
Couple of additional comments:
- I switched from standard JAVA Properties to DBB BuildProperties.
- I had to rename the `properties` variable to `props`. I have no idea, but when using `properties` then `properties.workDir` turned `null` within an each loop to extract the DD Outputs, even that @Field was defined ... I have not found that it is a reserved word or anything.
=> idz code review - add support for custom syslib

Pipeline/PackageBuildOutputs/ArtifactoryHelpers.groovy, Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md, Pipeline/PackageBuildOutputs/appArtifactory.properties, Pipeline/README.md
This PR ships a new pipeline sample to package the produced build outputs from a build with Dependency Based Build into a generic TAR file.
It contains of two parts:
- Packaging build outputs based after a successful DBB build
- ArtifactoryHelpers (as CLI or within code ) as a sample to upload or download to Artifactory.
However, as mentioned in the README, we recommend to leverage the existing Artifactory plugins available with your pipeline orchestrator.
It supersedes the existing PublishLoadModules script.
=> Package Build Outputs

Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy
This fixes #87 when buztool fails when the same input file is referenced in the ship list for a given member record several times.
=> ucd-packaging-script exclude main file from being a dependency input record

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md
Implementing #84 to raise a warning instead of an assertion no outputs found. Pipeline scripts should handle the case, when no outputs are found in the BuildReport.
Small update to the documentation
=> Enhancements PackageBuildOutputs

Utilities/WebAppCleanUp/README.md, Utilities/WebAppCleanUp/WebAppCleanUp.groovy
This enhancement is to support passing a file which contains DBB WebApp information. Using the --prop parameter, user can supply the absolute or relative path to a file that contains the necessary information to connect to the DBB WebApp server. The values in the file can still be overiden by CLI options (--url, --id, --pw, --pwFile).
The property file 'user.properties' is the valid sample file to be customized and to be used in the --prop parameter.
=> Enhancement to the WebAppCleanup script

Utilities/DeletePDS/DeletePDS.groovy, Utilities/DeletePDS/README.md
The DeletePDS script can be used to delete datasets that matches the HLQ parameter given as input.
When a preview flag is set, the utility just lists the datasets that match the HLQ parameter.
=> Add support for DeletePDS script

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md, Pipeline/PackageBuildOutputs/packageBuildOutputs.properties
This is an enhancement  of the current version of the PackageBuildOutputs. The changes propose to
* Externalise the Map of last level qualifier to the DBB CopyMode into a property file.
* Allows to include additional build outputs from USS to the tar file via cli `--includeLogs` option or through the property `includeLogs` the property file (Comma-separated).
* Ability to configure the `deployTypeFilter` in the property file.
* lists the tar file contents when running in verbose mode
Please note, that the cli options have changed. `-prop/--propertyFile` for the Artifactory properties should be replaced with `-artifactory/--artifactoryPropertiesFile`. **Using `-prop/--propertyFile` is marked as deprecated** and might be removed in the next version.
=> Enhance PackageBuildOutputs sample

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy
Hi, I'm currently building a CI/CD for a mainframe project in Brazil.
Our DBB server was down last week, so I started working with fullbuild on our pipeline. Unfortunately when we package the artifacts a error emerged:
` Read build report data from /u/gds/gabcavl/workspace/ffac537e_1643646053/result/build.20220131.012121.021/BuildReport.json
Removing Output Records without deployType or with deployType=ZUNIT-TESTCASE 
Caught: java.lang.NullPointerException: Cannot get property 'label' on null object
java.lang.NullPointerException: Cannot get property 'label' on null object
at PackageBuildOutputs.run(PackageBuildOutputs.groovy:121)`
It occurs because BuildReport.json for fullBuild does not have a dbbserver entry with BUILD_RESULT, like below:
`
{
"id": "BUILD_RESULT_1",
"label": …
=> Bugfix on PackageBuildOutputs on parsing fullBuild Log

Pipeline/RunIDZCodeReview/README.md, Pipeline/RunIDZCodeReview/RunCodeReview.groovy, Pipeline/RunIDZCodeReview/codereview.properties
Added the possibility to specify a maximum acceptable return code, which can be specified either in the property file, or through the CLI option (which takes precedence). If none of these options is used, a default acceptable RC is set to 3 (which is the highest value considered as acceptable by IDz v15 Code Review feature).
=> Added support for maxRC defined in property file or with CLI option

Pipeline/RunIDZCodeReview/README.md, Pipeline/RunIDZCodeReview/RunCodeReview.groovy, Pipeline/RunIDZCodeReview/codereview.properties
This PR adds the support for using a Property Group file. This file is made mandatory by Code Review when there is no SYSLIB found by the script (either automatically when copybooks are referenced or when passed through the codereview_syslib property). The path to the Property Group file (XML file) can be set in the codereview.properties file or with a command-line option (which overrides the definition in codereview.properties, if any). The Property Group file must be a local property group file (as generated through IDz) and must be UTF-8 encoded on USS.
This PR also adds the support for specifying a code page for the files to be processed. When not specified, Code Review uses the IBM-037 code page. The code page can be specified through a command-line option or with the …
=> Support for Property Group file and code page

Migration/sclm/groovy/GenerateBuildProperties.groovy, Migration/sclm/groovy/GenerateBuildScripts.groovy, Migration/sclm/groovy/SclmExtract.groovy, Snippets/zUnitTestCase/RunZUnitJCL.groovy
This PR resolves class resolution issues from missing import statements after upgrading to Groovy 4.0. 
Import statements were added to files using the XmlSlurper & XmlParser classes.
=> Add missing import statements for Groovy 4

Pipeline/RunIDZCodeReview/RunCodeReview.groovy
New PR fixing issues with #136
The upgrade to the 1.1.3 toolkit introduced the capacity to remove ASA characters when saving spool output of JCLs into flat files on USS. However, this processing is not applicable to XML files and CSV files created by Code Review.
This fix disables the removing of ASA characters in spool outputs for the XML and CSV files generated by Code Review, making them available for additional processing.
Based on comments from Nikos from Handelsbanken, I've also changed the way the output files are saved when they DD names are available, even when the return code is higher than the expected Max RC.
=> Fix for the CodeReview script - Correct processing of the XML and CSV files

Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy
This PR is adding a verification that the buildResult record exists.
Users have reported that they were facing a NPE #131 when the build was not producing a buildResult, e.q running the build without a connection to the metadata store.
=> Verify that a buildResult record exits

.gitignore, Pipeline/README.md, Pipeline/SimplePackageDeploy/README.md, Pipeline/SimplePackageDeploy/SimplePackageDeploy.groovy, Pipeline/SimplePackageDeploy/SimplePackageDeploy.properties, README.md
target libraries
Signed-off-by: Anuprakash Moothedath <anuprakash.moothedath@ibm.com>
=> Added SimpleBuildReportDeploy script to deploy the build output to target libraries

Pipeline/DeployUCDComponentVersion/README.md, Pipeline/DeployUCDComponentVersion/ucd-deploy.groovy
This updates the ucd-deploy sample and enables it to work with the DBB 2.0 toolkit, which dropped the Apache HTTP client, also see #145 
A side-effect of the new API that is used: the script requires JAVA 11 to execute.
=> Remove usage of Apache Http Client in the UCD deploy sample

Pipeline/CreateUCDComponentVersion/README.md, Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy, Pipeline/PackageBuildOutputs/ArtifactRepositoryHelpers.groovy, Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md
This PR contains enhancements to the Packaging scripts (CreateUCDComponentVersion and PackageBuildOutputs) to correctly calculate cumulative packages, when using multiple Build Reports. The key used in the Map object, used to accumulate artifacts to be deployed, is formed of the member name and the deploy type, instead of the fully-qualified dataset name and member in the previous versions.
It also contains an enhancement to the ArtifactRepositoryHelpers script, to support retries when performing uploads or downloads to/from an Artifact Repository server.
=> Updates to packaging scripts

README.md, Templates/Common-Backend-Scripts/README.md, Templates/README.md
Adding references to the solution page
=> Links to IBM DevOps Acceleration Program Solution Page

Pipeline/CreateUCDComponentVersion/README.md, Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy, Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md
This PR adds support for zFS files in the two packaging scripts (UCDCreateComponentVersion and PackageBuildOutputs).
It leverages a specific record type introduced in zAppBuild to support zFS outputs from build (currently used in CRB, zCEE3 and zCEE2 processing). This USS_RECORD is an AnyTypeRecord implementation.
=> Packaging scripts update for zFS files

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/gitClone.sh
In some situations the git repository has a different name than what is used as the application for the build phase ( see `-a` for the templates, or `--application` in zAppBuild). Be aware, that subsequent steps of the templates leverage the application parameter to locate the git repository of the application that is processed in the pipeline.
In the case when the project/repository name differs to the application name, leverage the new option on the `gitClone.sh` script to specify the directory during the clone operation. 
The parameter is then used as the directory when cloning: https://git-scm.com/docs/git-clone#Documentation/git-clone.txt-ltdirectorygt
=> Pipeline templates - ability to specify the directory when cloning

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/packageBuildOutputs.sh
As reported in #191 - application and branch parameters become only mandatory when using the upload function to the artifact repository.
=> Update packaging backend script - application and branch are optional parameters

Pipeline/CreateUCDComponentVersion/applicationRepositoryProps.properties, Pipeline/PackageBuildOutputs/packageBuildOutputs.properties
With some recent enhancements in the Assembler.groovy to support the debug side file, it requires to specify the container mapping for the v2 packaging format.
See specified output
https://github.com/IBM/dbb-zappbuild/blob/d177891a59a41b0947eacaf1e1e5a7ca199ac13a/languages/Assembler.groovy#L380
=> Add container mapping entry for EQALANGX output of Assembler.groovy

Templates/Common-Backend-Scripts/wazideploy-deploy.sh, Templates/Common-Backend-Scripts/wazideploy-evidence.sh
This is fixing the scenario when a relative path is used to invoke the wazideploy-deploy.sh script. See reported defect #194 
It simplifies the validation of the workspace parameter.
=> Fix wazideploy-deploy.sh and wazideploy-evidence.sh backend scripts for relative workspace scenario

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/test/logs/testGenericWrapper-uss.log, Templates/Common-Backend-Scripts/test/testGenericWrapper.sh, Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
As indicated in #193, the pipeline backend scripts need to use shorter branch names.
This PR is refreshing the computation of the build conventions:
* Feature branches are prefixed with an `F`.
* Epic branches are prefixed with `E`.
* Hotfix branches are prefixed with `H`.
* Release Maintenance branches are prefixed with `R`.
| branch name  | computed hlq | 
| -------------  | ------------ |
|feature/42-new-mortgage-calculation |PIPELINE.MORTGAGE.F42 |
|feature/new-mortgage-calculation |PIPELINE.MORTGAGE.FNMC |
|feature/newmortgagecalculation |PIPELINE.MORTGAGE.FNEWMORT |
|release/rel-2.0.1  | PIPELINE.MORTGAGE.R201 | 
|hotfix/rel-2.0.1/52-fix-mortgage-calculation |PIPELINE.MORTGAGE.R201.H52 |
|epic/ai-fraud-detection |PIPELINE.MORTGAGE.EAFD | …
=> Compute build parameters on updated branch naming conventions

Templates/Common-Backend-Scripts/packageBuildOutputs.sh, Templates/Common-Backend-Scripts/ucdPackaging.sh
The two templates `packageBuildOutputs.sh` and `ucdPackaging.sh` previously have resolved the dbb runtime via the PATH environment variable.
The build wrapper script leveraged the `DBB_HOME` environment variable.
The below updates aim for consistency and align with the DBB environment variables.
=> Leverage DBB_HOME to resolve DBB toolkit in template scripts

Templates/Common-Backend-Scripts/pipelineBackend.config, Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
Creating a cumulative package from the build pipeline for feature branches, is a desirable aspect of the development workflow, and would improve the workflow to [package and deploy a feature for testing in controlled test environments](https://ibm.github.io/z-devops-acceleration-program/docs/branching-model-supporting-pipeline#package-and-deploy-a-feature-for-testing-in-controlled-test-environments).
This PR lets the DevX team configure the common backend scripts and the behaviour of feature branch pipelines. 
The build phase of feature branch pipelines can be configured to always build all changes for the feature along with the impact build capability of DBB. This is the default build behaviour.
=> Common Backend Scripts - Enabling cumulative feature branch builds

Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
This is implementing defect #217 
The common backend scripts missed to add the debug `--debug` flag for the basic build pipeline for the main branch.
While the `--debug` is a mandatory field for this workflow, it is sufficient to just remove the condition and append the debug options.
=> Common Backend Scripts - Add debug flag to Basic Pipeline workflow for main branch

Templates/AzureDevOpsPipeline/azure-pipelines.yml
This is addressing an issue introduced with #216 . 216 has missed to reference the verbose flag as a variable.
=> AzureDevOps Pipeline to reference variable for verbose logging

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/gitClone.sh
This is implementing #224 to correctly evaluate the return code of the invocation of the git command.
=> Uplift error handling of gitClone.sh backend script

Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
This is implementing the fix to address #232 to correctly pass the computed property overrides to the `dbbBuild.sh` script.
=> Correction to pass property overrides to dbbBuild.sh

Templates/AzureDevOpsPipeline/templates/tagging/createReleaseCandidate.yml, Templates/GitlabCIPipeline/.gitlab-ci.yml
This is implementing 
* correct computation of the baseline tag for computing the next release.
* and fixes the computation of release candidate numbers as reported in #230
=> Update computation of release and release candidate tags for release branches

Pipeline/PackageBuildOutputs/ArtifactRepositoryHelpers.groovy, Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md, Pipeline/PackageBuildOutputs/appArtifactRepository.properties
This is implementing the enhancement to allow the user to define the HTTP Client protocol version for the HTTP Request. 
See enhancement request #237 .
The issue was observed implementing a pipeline with the Nexus in the OSS version.
The user can set the httpClient protocol version via:
* CLI parm for PackageBuildOutputs
* Property Setting for application specific artefact repository settings
* CLI for ArtifactRepositoryHelpers.groovy
=> Implement option to set HTTP Client Protocol version for ArtifactRepositoryHelpers

Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy
This is implementing issue #222 to return with a non-zero return code when there were not items found that need to be packaged.
Any subsequent scripts can assess the return code instead of having to parse the log output.
=> Exit with non-zero return code when BuildReport does not contain outputs

Templates/Common-Backend-Scripts/dbbBuild.sh
This is implementing #248 to allow the Common Backend Scripts to be used with the DBB FileMetadatastore.
=> Turn JDBC id and password into optional parameters

Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
This implements issue #247 to improve the management of branch names that do not match the recommended branching model. 
The recommended naming conventions are documented at https://ibm.github.io/z-devops-acceleration-program/docs/git-branching-model-for-mainframe-dev/#naming-conventions
=> Manage branch names that do not follow naming conventions

Templates/GitlabCIPipeline/.gitlab-ci.yml, Templates/GitlabCIPipeline/README.md
This is enhancing the existing GitLab template with the following: 
* Leverage the `workflow` keyword to control the pipeline behaviour - see https://docs.gitlab.com/ee/ci/yaml/index.html#workflow
* Refactor the rules, when stages are executed
* Persist Wazi Deploy evidences for later reporting capabilities
* Move to `zowe rse issue unix-shell` that was released with IBM® RSE API Plug-in for Zowe CLI Version 4.2.0 on 16 March 2024, bringing a new option for long-running commands allowing a streaming of log output to the script that invokes it.
=> Uplift GitLab template and persist WD evidences

Templates/GitHubActionsPipeline/README.md
The links to the various workflow files in the [Pipeline usage](https://github.com/IBM/dbb/tree/main/Templates/GitHubActionsPipeline#pipeline-usage) section of the GitHub Actions template Readme currently lead to a 404 page. This PR adds the `.github/` folder into the URLs to fix them.
=> Fix GitHub Action template Readme links

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy
This PR contains various fixes and an enhancement to the error management in the script.
=> Enhanced Packaging process

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/utilities/WaziDeployManifestGenerator.groovy
This is implementing the enhancement #265 .
This PR extends the existing logic and parses the `DELETE_RECORDS` created by zAppBuild, and injects them into the Wazi Deploy Application Manifest file under the `deleted_artifacts` group.
=> PackageBuildOutputs creating delete manifest records for Wazi Deploy Application Manifest

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/pipelineBackend.config, Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
This is implementing #279 to use `git merge-base` to identify the point in the history when a topic branch was forked.
The new default behaviour for feature branch pipelines is to use the **merge-base** commit: In conjunction with zAppBuild, the result of this configuration is that feature branches pipelines will always identify all the changes added to the topic branch as changes, to build a consistent, cumulative preliminary package for the feature branch. 
Choosing this approach, there will be two options to deal with the process of integrating changes from main branch (or any other target) into the feature branch:
* `git merge` will commit all commits from main into the feature branch, and the merge-base strategy for computing the baseline commit hash will identify the existing …
=> Enable common backend scripts to compute merge-base for feature branch pipelines

.gitattributes, Pipeline/PackageBuildOutputs/packageBuildOutputs.properties
This PR adds a copy mode for artifacts that are in datasets OBJ (typically Object decks, which are meant to be copied as binary).
It also add an encoding for YAML files (either .yaml or .yml extensions).
=> Added support for OBJ artifacts and switched to IBM-1047 tags for YAML files

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md, Pipeline/PackageBuildOutputs/packageBuildOutputs.properties, Pipeline/PackageBuildOutputs/utilities/concertBuildManifestGenerator.groovy, Pipeline/PackageBuildOutputs/utilities/sbomGenerator.groovy
This pull request is to implement a feature integrating z/OS builds with [IBM Concert](https://www.ibm.com/products/concert) This includes changes within the packaging script to create concert specific SBOM manifest or configurations. IBM Concert requires zOS Application builds to generate build config in the format https://github.ibm.com/roja/sample_app_data/blob/main/102/system-z/build-config-sample.yaml so that it can be supplied to concert dashboards. This enables zOS application changes to be visible in Concert dashboards along with the rest of the enterprise applications.
=> Feature/concert SBOM integration

.gitattributes, Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md, Pipeline/PackageBuildOutputs/packageBuildOutputs.properties, Pipeline/PackageBuildOutputs/utilities/WaziDeployManifestGenerator.groovy, Pipeline/PackageBuildOutputs/utilities/applicationDescriptorUtils.groovy
This PR adds support for Application Descriptor files and baseline packages.
Application Descriptor files are YAML files in the application's Git repository that describes the content of the application. If the path to the application's folder checked out on USS is provided through the `--applicationFolderPath` parameter, the Application Descriptor file `applicationDescriptor.yml` is looked up is parsed to get the list of include files that are public, that can be consumed by other applications.
If the path to a baseline package is provided through the `baselinePackage` parameter, the baseline package is expanded in the temporary folder, before its content can be overridden by artifacts that are documented in the Build Report provided as input.
The structure of the archive is …
=> Ability to publish interfaces via the tar file using the Application Descriptor

Templates/Common-Backend-Scripts/dbbBuild.sh, Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
This addresses broken preview mode #303 .
In case the CBS compute the build type, the preview option will be appended to the build build configuration.
In case the has overridden the build type via the cli argument `-t`, the preview mode will not be considered.
This is aligned to the implementation of the zBuilder.sh wrapper
=> Fix Common Backend script to correctly support preview build scenario

Templates/Common-Backend-Scripts/dbbBuild.sh
This PR for the Common Back-end Scripts Template's `dbbBuild.sh` file adds handling for the use case where the only source changes are file deletion (i.e. files are only listed in `deletedFilesList.txt` but not in `buildList.txt`).
With this PR, the pipeline can continue (e.g. with packaging) in this use case, instead of stopping with RC=4.
Resolves #305
=> Handle delete-only case in dbbBuild.sh

Migration/jcl/README.md
The word 'local' seems redundant and (at least to me) potentially confusing.
Also the fenced block for the usage description wasn't terminated so the following Markdown wasn't formatting correctly.
=> Corrections to JCL migration sample README

Pipeline/PackageBuildOutputs/ArtifactRepositoryHelpers.groovy
The script ArtifactRepositoryHelpers.groovy has a built-in mechanism to retry failed communication attempts. That mechanism repeats a request up to ten times if that request fails. Whether or not a request has failed depends on its HTTP response code. The current version of the script only accepts a response code of 200 (OK) as successful. This leads to the unfortunate behavior that an upload will be repeated ten times when an artifact repository replies with the valid response code 201 (Created).
If repeated uploads of the same file are permitted by the artifact repository, the overall return code of the script becomes zero since the last HTTP response is delivered as finalResponse, no matter if successful or not. A response code of 201 is accepted as valid in the method …
=> no retry on http status code 201

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/deleteWorkspace.sh
Add the following checks against pipeline deletion of high-level directories in Common Back-end Scripts `deleteWorkspace.sh`:
- `-P` option
- working directory path length check
Resolves #329
=> Issue 329 - Improve checks against deletion of high-level directories in CBS cleanup

Templates/Common-Backend-Scripts/README.md
wazideloy changed to wazideploy in common backend scripts documentation
=> Fixed typo
