Pipeline/README.md, Pipeline/RunIDZCodeReview/README.md, Pipeline/RunIDZCodeReview/RunCodeReview.groovy, Pipeline/RunIDZCodeReview/codereview.properties
This sample parses the dbb build report and assembles an JCL to run the IDZ Code Review application.
=> idz code review sample based on dbb build report

Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy
=> Consistent property name for dbb build result url in dbb-ucd-packaging script

Pipeline/CreateUCDComponentVersion/README.md, Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy
=> Support packaging of outputs declared in CopyToPDS

Pipeline/CreateUCDComponentVersion/README.md, Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy
=> Pipeline: Adapt the UCD packaging script with UCD 7.1.x

Pipeline/RunIDZCodeReview/README.md, Pipeline/RunIDZCodeReview/RunCodeReview.groovy, Pipeline/RunIDZCodeReview/codereview.properties
See: https://github.com/IBM/dbb/issues/65
=> Code Review sample groovy script does not allow using custom rules

Pipeline/DeployUCDComponentVersion/README.md, Pipeline/DeployUCDComponentVersion/ucd-deploy.groovy, Pipeline/README.md
This is a basic groovy script that allow to perform the deployment of a UCD application into a dedicated environment. This script only use APIs from libraries shipped with DBB Toolkit and don't need extra libraries in the Java class path.
@dennis-behm Can you review it ASAP ? We will use it in a future tutorial for GitLab CI/CD.
Thanks
=> Add a basic UCD application deployment groovy script

Migration/jcl/groovy/JCLtoDBB.groovy
Signed-off-by: Anuprakash Moothedath <Anuprakash.Moothedath@ibm.com>
=> Updated JCLtoDBB.groovy to map the DD parms to align with BPXWDYN

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy
=> Organize import statements of PackageBuildOutputs

Pipeline/PackageBuildOutputs/packageBuildOutputs.properties
Signed-off-by: Jean-Yves BAUDY <baudy.jy@fr.ibm.com>
=> Update packageBuildOutputs.properties to include JCL type

README.md, Utilities/PermissionCheck/README.md, Utilities/PermissionCheck/checkDBBPermission.groovy
This script leverages the same API like DBB to check if the provided username is member of one of the predefined DBB groups.
=> Permission Checker Util

Migration/ReportMigration/README.md
Adds a warning about losing custom template changes and a note about the CopyToPDS record defect that has a fix coming.
=> Added a warning to the Report Migration README.

Templates/Common-Backend-Scripts/wazideploy-deploy.sh, Templates/Common-Backend-Scripts/wazideploy-generate.sh
=> Update wazideploy backend scripts to enable debug option

Templates/AzureDevOpsPipeline/azure-pipelines.yml
=> Azure pipeline template - Remove redundant verbose flag

Pipeline/CreateUCDComponentVersion/README.md, Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy
Hi @dennis-behm Found some improvements in UCD packaging documentation.
=> Minor improvements to CreateUCDComponentVersion files

Templates/GitlabCIPipeline/.gitlab-ci.yml
Few fixes (mainly typos) and a missing tag section which could cause issues when the wrong agent is picked up to execute the task.
=> Few fixes (typos) and missing tag section

Templates/GitlabCIPipeline/.gitlab-ci.yml
Fixed the variable name in the "Create Production version" step which was incorrect.
Fixed other minor typos.
=> Fix for the releaseType variable and few other minor fixes

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md, Pipeline/PackageBuildOutputs/utilities/sbomGenerator.groovy
This PR implements the generation of an SBOM following the CycloneDX 1.5 specification.
It leverages the content of the DBB Build Report, to collect the required information and generate an SBOM file describing the content of the package. It documents the files that are meant to be deployed.
=> First implementation of the SBOM generation

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/utilities/sbomGenerator.groovy
Fixed the SBOM generation for files described in a USS_RECORD (based on the AnyType Record).
=> Fixed SBOM generation for USS files

Templates/Common-Backend-Scripts/utilities/dbbBuildUtils.sh
=> Remove resetting of build type setting in dbbBuildUtils

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/generateCleanupCommands.sh
This common backend script allows to perform automated cleanup of the DBB Collections and Build Groups and the Build datasets.
This implements #254
=> Cleanup Utility to remove stale DBB objects and build libraries

Templates/Common-Backend-Scripts/prepareLogs.sh
This implements the validation that the log directory exists + some minor cleanup. See #266
=> CBS prepareLogs.sh - Verify that log directory exists

Templates/Common-Backend-Scripts/prepareLogs.sh
This is fixing the prepareLogs defect reported in #270
=> Fix prepareLogs.sh

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/packageBuildOutputs.properties
This is addressing the issue raised in #272
=> Fix PackageBuildOutputs.groovy from overriding from the config from the properties file

Templates/Common-Backend-Scripts/dbbBuild.sh
This PR fixes the classpath when using the DBB Logger in dbbBuild.sh.
=> Fixed classpath for DBB Logger

Migration/jcl/groovy/JCLtoDBB.groovy
ScriptLoader is not used by JCLtoDBB.groovy
=> Remove ScriptLoader

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/utilities/dbbzBuilderUtils.sh, Templates/Common-Backend-Scripts/zBuilder.sh
This adds a new common backend script for the DBB zBuilder framework. It ships with its own utilities that is able to determine the baselineReference and the mainBuildBranch override if necessary.
=> Common Backend script for DBB zBuilder

Schema/LegacyVersions/buildConfigurationSchema-v1.0.0.json, Schema/README.md, Schema/applicationConfigurationSchema.json
Sets a system in place for providing legacy schema versions as well as a dynamically updating latest schema version. Kept as draft until 3.0.1 release.
=> Schema 1.0.1 for DBB 3.0.1

Pipeline/PackageBuildOutputs/PackageBuildOutputs.groovy, Pipeline/PackageBuildOutputs/README.md, Pipeline/PackageBuildOutputs/packageBuildOutputs.properties
While adding files with files extension *.log, *.yml into the tar file, the script was omitting those files.
=> Fix for the problem that a customer faced with file extensions in packagebuildoutputs.groovy

Schema/LegacyVersions/buildConfigurationSchema-v1.0.1.json
Updated build configuration to 1.0.2 for the DBB 3.0.2 release and archived the 1.0.1 version.
=> Schema 1.0.2 for DBB 3.0.2

Templates/Common-Backend-Scripts/README.md, Templates/Common-Backend-Scripts/gitClone.sh
Optimised clone configuration for gitClone.sh to use a partial clone. 
This PR introduces a tree less clone as outlined in https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
=> Optimised Clone options in gitClone.sh

Schema/LegacyVersions/buildConfigurationSchema-v.1.0.2.json
v1.0.3 Schema update for DBB 3.0.3 release
=> Schema 1.0.3 for DBB 3.0.3
